# General
device: "cuda"
large_model: "opt-350m"
model_dtype: "float16"

# training parameters
lr: 0.000005
iterations: 200
eval_iterations: 20

# dataset
dataset: "yahoo_answers"
train_batch_size: 32
test_batch_size: 32

# zo parameters
estimator_type: "vanilla"
grad_estimate_method: "rge-central"
pert_distribution: "gaussian"
num_pert: 1
mu: 0.001

# MISC
seed: 1234
